config/routes.rb
Rails.application.routes.draw do
  root 'pictures#index'

  devise_for :users

  resources :pictures
  resources :users

end

app/models/image.rb
class Image < ActiveRecord::Base
end

app/models/picture.rb
class Picture < ActiveRecord::Base

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true, length: {maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  # before_action :authenticate_user!

  def new
    @picture = Picture.new
  end

  def create
    @picture = Picture.new(picture_params)
    if @picture.save
      redirect_to pictures_url
    else
      render 'new'
    end
  end

  def index
    @pictures = Picture.all
  end

  private

  def picture_params
    params.require(:picture).permit(:title, :image)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_url
      else render 'new'
    end
  end
  def index
    @users = User.all
  end

  private
  def user_params
    params.require(:user).permit(:first_name,:second_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/images/new.html.erb
<h1>Images#new</h1>
<p>Find me in app/views/images/new.html.erb</p>
<%= form_for @image do |f| %>
<%= f.label :title %>
<%= f.text_area :title %>
<%= f.submit %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Shop Admin</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Images', pictures_path %></li>
        <li><%= link_to 'Categories' %></li>
      </ul>
      <ul class="nav navbar-nav">
        <li><%= link_to 'Профиль'.html_safe %></li>
        <li><%= link_to '<i class="fa fa-sign-out pull-right"></i> Выйти'.html_safe, destroy_user_session_path, method: :delete %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gallery</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>


<body>
<%= render 'layouts/navbar' %>
<div class="container">
  <%= yield %>
</div>
</body>

</html>

app/views/pictures/index.html.erb
<h1>Images</h1>
<div>
<%= link_to 'Add picture', new_picture_path %>
</div>
  <% @pictures.each do |pic| %>
    <%= pic.title %>
    <%= image_tag pic.image.url(:medium) %>
    <br>
<% end %>

app/views/pictures/new.html.erb
<h1>Images#new</h1>
<%= form_for @picture do |f| %>
    <div>
      <%= f.label :title %>
      <%= f.text_area :title %>
    </div>
    <div>
      <%= f.label :image %>
      <%= f.file_field :image %>
    </div>
    <div>
      <%= f.submit %>
    </div>
<% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<% @users.each do |user| %>
<%= user.first_name %>
    <br>
<%= user.second_name %>
<% end %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<%= form_for @user do |f| %>
    <div>
    <%= f.label :first_name %>
      <%= f.text_area :first_name %>
    </div>

    <fiv>
      <%= f.label :second_name %>
      <%= f.text_area :second_name %>
    </fiv>

    <div>
      <%= f.submit %>
    </div>
<% end %>